[package]
name = "mnu"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[workspace]
members = [
    "crates/csprng",
    "crates/PlugKit/plugkit",
    "crates/PlugKit/plugkit-macros",
    "crates/PlugKit/plugkit-sys",
    "crates/time-core",
    "examples/user",
    "examples/plugkit/test",
]
default-members = [".", "examples/user"]
exclude = ["examples/boot"]

[lib]
path = "src/lib.rs"
test = false
bench = false
doctest = false

[[bin]]
name = "kernel"
path = "src/entry.rs"
test = false
bench = false
required-features = ["kernel-bin"]

[target.'cfg(any(target_os = "none", target_os = "uefi"))'.dependencies]
mnu-abi = { git = "https://github.com/mochiOS/mnu", package = "mnu-abi" }
linked_list_allocator = "0.10.5"
mochios-csprng = { git = "https://github.com/mochiOS/mnu", package = "mochios-csprng" }
mochios-time-core = { git = "https://github.com/mochiOS/mnu", package = "mochios-time-core" }
sha2 = { version = "0.10.8", default-features = false }
spin = "0.9"
x86_64 = "0.15"

[dependencies]
plugkit-sys = { git = "https://github.com/mochiOS/mnu", package = "plugkit-sys" }

[features]
default = ["kernel-bin"]
kernel-bin = []
kcfi = []
cet-ibt = []
cet-shadow-stack = []

[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
