//! システムコール ABI の共通定義

pub use mnu_abi::{
    SyscallNumber, EACCES, EAGAIN, EBADF, ECHILD, EEXIST, EFAULT, EFBIG, EINVAL, EIO, EISDIR,
    EMFILE, ENODATA, ENOENT, ENOMEM, ENOSPC, ENOSYS, ENOTDIR, ENOTSUP, ENOTTY, ENXIO, EOVERFLOW,
    EPERM, EPIPE, ERANGE, EROFS, ESRCH, SUCCESS,
};
