[package]
name = "user"
version = "0.1.0"
edition = "2024"

[lib]
path = "src/lib.rs"

[dependencies]
mnu-abi = { git = "https://github.com/mochiOS/mnu", package = "mnu-abi" }

[[bin]]
name = "user"
path = "src/main.rs"
test = false
bench = false
harness = false

[[bin]]
name = "captest"
path = "src/captest_main.rs"
test = false
bench = false
harness = false
